### ISSUE TITLE
Popular and trending packages from libraries.io

### ISSUE THREAD

**Issue by agjohnson** [rtfd/pydoc.io#20]
Integrate with libraries.io for trending and popular package information. This will be used on the front page to link to documentation.

Keep in memory or cache the response or something. We just need this to update periodically for the front page display.

**Comment by ericholscher** [comment]
https://libraries.io/api/search?api_key=edbc9c697f3adbe371c0003bf5c7ebeb&platforms=Pypi&sort=rank
